# Generated by Django 4.2.16 on 2024-11-17 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Farmer', 'Farmer'), ('Coordinator', 'Coordinator')], default='Farmer', max_length=15)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True, unique=True)),
                ('role', models.CharField(max_length=15, null=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('village', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to='base.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True)),
                ('crop_type', models.CharField(max_length=50)),
                ('variety', models.CharField(max_length=100)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('field_number', models.CharField(max_length=100)),
                ('fertilizer_usage', models.TextField(blank=True, null=True)),
                ('condition', models.CharField(default='Healthy', max_length=100)),
                ('problems', models.TextField(default=1)),
                ('irrigation_type', models.CharField(choices=[('Drip', 'Drip'), ('Sprinkle', 'Sprinkle'), ('Pump', 'Pump')], default='Drip', max_length=50)),
                ('season', models.CharField(choices=[('Kharif', 'Kharif'), ('Rabi', 'Rabi'), ('Summer', 'Summer')], default='Rabi', max_length=50)),
                ('land_type', models.CharField(choices=[('Jirayati', 'Jirayati'), ('Bagayati', 'Bagayati'), ('Koradwahi', 'Koradwahi'), ('Kharepat', 'Kharepat')], default='Jirayati', max_length=50)),
                ('crop_category', models.CharField(choices=[('Food Crops', 'Food Crops'), ('Fodder Crops', 'Fodder Crops'), ('Fruit Crops', 'Fruit Crops'), ('Spices', 'Spices'), ('Vegetables', 'Vegetables'), ('Flower Crops', 'Flower Crops')], default='Food Crops', max_length=50)),
                ('farmer_type', models.CharField(choices=[('Land Owner', 'Land Owner'), ('Tenant', 'Tenant'), ('Cultivator', 'Cultivator'), ('Contract', 'Contract')], default='Land Owner', max_length=50)),
                ('photo_crop_condition', models.ImageField(blank=True, null=True, upload_to='crop_images/')),
                ('area_in_acres', models.DecimalField(decimal_places=2, default=1, max_digits=5, null=True)),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='base.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CoordinatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True, unique=True)),
                ('role', models.CharField(max_length=15, null=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('village', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_profile', to='base.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='base.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, through='base.CartItem', to='base.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
