# Generated by Django 5.0.2 on 2024-08-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='crop_condition',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='crop_problem',
            field=models.TextField(default='No problem reported'),
        ),
        migrations.AddField(
            model_name='profile',
            name='crop_type',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='onsite_person_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='survey_number',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='taluka',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='village',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
