# Generated by Django 5.0.7 on 2024-08-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile_crop_condition_profile_crop_problem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='crop_condition',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='crop_problem',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='crop_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='onsite_person_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='survey_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='taluka',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='village',
        ),
    ]
