# Generated by Django 4.2.15 on 2024-08-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_crop_profile_user_profile_user_type_farmerprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
