# Generated by Django 4.2.15 on 2024-08-31 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_crop_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Crop', to='base.profile'),
        ),
    ]
