# Generated by Django 4.2.15 on 2024-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_crop_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='problems',
            field=models.TextField(blank=True, null=True),
        ),
    ]
