# Generated by Django 4.2.15 on 2024-09-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_crop_condition_crop_problems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='problems',
        ),
    ]
