# Generated by Django 4.2.15 on 2024-09-03 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_crop_area_in_acres_alter_crop_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Crop', to='base.profile'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='area_in_acres',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='condition',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crop',
            name='crop_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='crop',
            name='fertilizer_usage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='irrigation_type',
            field=models.CharField(choices=[('Drip', 'Drip'), ('Sprinkle', 'Sprinkle'), ('Pump', 'Pump')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='photo_or_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='problems',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='crop',
            name='season',
            field=models.CharField(choices=[('Rabi', 'Rabi'), ('Kharif', 'Kharif')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
