# Generated by Django 4.2.15 on 2024-09-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_crop_profile_alter_crop_area_in_acres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='area_in_acres',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='irrigation_type',
            field=models.CharField(choices=[('Drip', 'Drip'), ('Sprinkle', 'Sprinkle'), ('Pump', 'Pump')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='crop',
            name='photo_or_information',
            field=models.TextField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='problems',
            field=models.TextField(default=1),
        ),
        migrations.AlterField(
            model_name='crop',
            name='season',
            field=models.CharField(choices=[('Rabi', 'Rabi'), ('Kharif', 'Kharif')], default=1, max_length=50),
        ),
    ]
