# Generated by Django 4.2.15 on 2024-09-04 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_crop_area_in_acres_alter_crop_irrigation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='irrigation_type',
            field=models.CharField(choices=[('Drip', 'Drip'), ('Sprinkle', 'Sprinkle'), ('Pump', 'Pump')], default='Drip', max_length=50),
        ),
        migrations.AlterField(
            model_name='crop',
            name='photo_or_information',
            field=models.ImageField(blank=True, null=True, upload_to='crop_images/'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Crop', to='base.profile'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='season',
            field=models.CharField(choices=[('Rabi', 'Rabi'), ('Kharif', 'Kharif')], default='Rabi', max_length=50),
        ),
    ]
