# Generated by Django 4.2.15 on 2024-09-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_crop_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
