# Generated by Django 4.2.15 on 2024-09-04 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_crop_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Crop', to='base.profile'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=None),
        ),
    ]
