# Generated by Django 4.2.15 on 2024-09-04 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_coordinatorprofile_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatorprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_profile', to='base.profile'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to='base.profile'),
        ),
    ]
