# Generated by Django 4.2.15 on 2024-09-04 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_coordinatorprofile_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='photo_or_information',
            new_name='photo_crop_condition',
        ),
        migrations.AlterField(
            model_name='coordinatorprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_profile', to='base.profile'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to='base.profile'),
        ),
    ]
