# Generated by Django 4.2.15 on 2024-09-06 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_crop_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='crop_category',
            field=models.CharField(choices=[('Food Crops', 'Food Crops'), ('Fodder Crops', 'Fodder Crops'), ('Fruit Crops', 'Fruit Crops'), ('Spices', 'Spices'), ('Vegetables', 'Vegetables'), ('Flower Crops', 'Flower Crops')], default='Food Crops', max_length=50),
        ),
        migrations.AddField(
            model_name='crop',
            name='farmer_type',
            field=models.CharField(choices=[('Land Owner', 'Land Owner'), ('Tenant', 'Tenant'), ('Cultivator', 'Cultivator'), ('Contract', 'Contract')], default='Land Owner', max_length=50),
        ),
        migrations.AddField(
            model_name='crop',
            name='land_type',
            field=models.CharField(choices=[('Jirayati', 'Jirayati'), ('Bagayati', 'Bagayati'), ('Koradwahi', 'Koradwahi'), ('Kharepat', 'Kharepat')], default='Jirayati', max_length=50),
        ),
        migrations.AlterField(
            model_name='crop',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='base.profile'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='season',
            field=models.CharField(choices=[('Kharif', 'Kharif'), ('Rabi', 'Rabi'), ('Summer', 'Summer')], default='Rabi', max_length=50),
        ),
    ]
